#!/bin/sh

REPOS="$1"
REV="$2"

# updating sneer 
/usr/bin/svn up /usr/local/sneer/sneer
# updating wheel
/usr/bin/svn up /usr/local/sneer/java/

# Compiling Server.
cd /usr/local/sneer/sneer/bin

/usr/lib/jdk1.5.0_07/bin/javac -encoding UTF-8 -d .  -sourcepath ../src:../../java/src/  ../src/sneer/server/Server.java ../bootstrap/src/sneer/strap/*.java

# killing the running server.
qtdproc=`/bin/ps -ef | /bin/grep sneer.server.Server | /bin/grep -v "/bin/grep sneer.server.Server" | /usr/bin/wc -l`

while [ $qtdproc -gt 0 ]
do
  # if the number of the process is > 10000
  numproc=`/bin/ps axo pid,command | /bin/grep sneer.server.Server | /bin/grep -v "/bin/grep sneer.server.Server" | cut -d\  -f1`

  /bin/kill -9 $numproc
	
  numproc=`/bin/ps axo pid,command | /bin/grep sneer.server.Server | /bin/grep -v "/bin/grep sneer.server.Server" | cut -d\  -f2`

  /bin/kill -9 $numproc

  /bin/sleep 4

  qtdproc=`/bin/ps -ef | /bin/grep sneer.server.Server | /bin/grep -v "/bin/grep sneer.server.Server" | /usr/bin/wc -l`

done

# Starting the new version
cd /usr/local/sneer/sneer
/usr/lib/jdk1.5.0_07/bin/java -classpath . sneer.server.Server & 

